### ISSUE TITLE
Smoke Detection

### ISSUE THREAD

**Issue by mudasarK** [hardik0/Deep-Learning-with-GoogleColab#1]
Hi, I tried to run your Darknet_YOLOv3_Cigarette_Smoking_Detection.ipynb, but issue is of data, can you please help me out with smoke data. where can I get it? 
Thank you

**Comment by hardik0** [comment]
hey @mudasarK ,
As per my knowledge no dataset is available on the internet, I scraped data from Google and others (Pinterest, Flickr) website.

**Comment by mudasarK** [comment]
Hi @hardik0,
thank you for the response, is it feasible if you share that dataset with me?
I tried to crop some images and trained but it is not working properly.

**Comment by hardik0** [comment]
I only tried on small amounts of data, You can use various data augmentation techniques or use more images for better accuracy. 
Annotation tools: [click here](https://github.com/AlexeyAB/darknet#how-to-mark-bounded-boxes-of-objects-and-create-annotation-files)
Dataset: [drive](https://drive.google.com/open?id=1rmOu-sYmBv1hhoeKwz3FWDHg2Z4XYWjy)

**Comment by mudasarK** [comment]
Thank you for your answer.
