### ISSUE TITLE
Is there any way i can get the trained gun detector model?

### ISSUE THREAD

**Issue by version0chiro** [hardik0/Deep-Learning-with-GoogleColab#3]

**Comment by hardik0** [comment]
**No.** You have to invest your time to train your own model and nowadays annotated dataset is easily available: [Open Images Dataset](https://storage.googleapis.com/openimages/web/index.html)
with help of google colab + yolo you can train your model

**Comment by version0chiro** [comment]
Oh alright. I just had a deadline and wanted to check if this will work in the desired format. Anyway, thanks for help.
